"""
Platform Context Objects.
Context management for NCP pipeline execution.
"""
from typing import Optional, Dict, Any, List
from uuid import UUID
from dataclasses import dataclass, field
from enum import Enum


class NCPStage(Enum):
    """Nutrition Care Process stages."""
    INTAKE = "intake"
    ASSESSMENT = "assessment"
    DIAGNOSIS = "diagnosis"
    INTERVENTION = "intervention"
    MONITORING = "monitoring"


@dataclass
class ClientContext:
    """
    Client context for NCP pipeline execution.
    
    Carries client information and state through the pipeline.
    No business logic - data container only.
    """
    client_id: UUID
    current_stage: NCPStage = NCPStage.INTAKE
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def __post_init__(self):
        """Validate context after initialization."""
        if not isinstance(self.client_id, UUID):
            raise ValueError("client_id must be a UUID")


@dataclass
class IntakeContext:
    """
    Intake stage context.
    
    Contains raw and normalized intake data.
    """
    client_id: UUID
    intake_id: Optional[UUID] = None
    raw_input: Optional[Dict[str, Any]] = None
    normalized_input: Optional[Dict[str, Any]] = None
    source: Optional[str] = None  # manual | upload | ai_extracted


@dataclass
class AssessmentContext:
    """
    Assessment stage context.
    
    Contains assessment snapshot and status.
    """
    client_id: UUID
    assessment_id: Optional[UUID] = None
    intake_id: Optional[UUID] = None
    assessment_snapshot: Optional[Dict[str, Any]] = None
    assessment_status: Optional[str] = None  # draft | finalized


@dataclass
class DiagnosisContext:
    """
    Diagnosis stage context.
    
    Contains medical and nutrition diagnoses.
    """
    assessment_id: UUID
    medical_conditions: list = field(default_factory=list)
    nutrition_diagnoses: list = field(default_factory=list)


@dataclass
class MNTContext:
    """
    MNT (Medical Nutrition Therapy) context.
    
    Contains MNT constraints and rules applied.
    """
    assessment_id: UUID
    macro_constraints: Optional[Dict[str, Any]] = None
    micro_constraints: Optional[Dict[str, Any]] = None
    food_exclusions: Optional[list] = None
    rule_ids_used: list = field(default_factory=list)


@dataclass
class TargetContext:
    """
    Target calculation context.
    
    Contains calculated nutrition targets.
    """
    assessment_id: UUID
    calories_target: Optional[float] = None
    macros: Optional[Dict[str, Any]] = None
    key_micros: Optional[Dict[str, Any]] = None
    calculation_source: Optional[str] = None  # bmr | tdee | custom


@dataclass
class MealStructureContext:
    """
    Meal structure context.
    
    Contains structural meal plan skeleton (no food items).
    Defines the shape of the day - number of meals, timing windows,
    and energy weights (relative allocation).
    
    Key Design Rules:
    - Nutrition-agnostic: No references to kcal, protein_g, fat_g, carbs_g
    - Energy allocation is RELATIVE: energy_weight values sum to 1.0
    """
    assessment_id: UUID
    meal_count: int
    meals: List[str]  # ["breakfast", "lunch", "snack", "dinner"]
    timing_windows: Dict[str, List[str]]  # {"breakfast": ["07:30", "09:00"]}
    energy_weight: Dict[str, float]  # {"breakfast": 0.225, "lunch": 0.325, ...} - Sum must equal 1.0
    flags: List[str] = field(default_factory=list)


@dataclass
class ExchangeContext:
    """
    Exchange allocation context.
    
    Contains exchange allocations per meal generated by ExchangeSystemEngine.
    Also contains per-meal nutrition targets calculated from daily totals × energy_weight.
    """
    assessment_id: UUID
    exchanges_per_meal: Dict[str, Dict[str, int]]  # {"breakfast": {"cereal": 2, "pulse": 1, ...}, ...}
    per_meal_targets: Dict[str, Dict[str, float]]  # {"breakfast": {"calories": 450, "protein_g": 18, "carbs_g": 56.25, "fat_g": 14.625}, ...}
    notes: Optional[Dict[str, Any]] = None  # {"medical_modifiers_applied": [...], "ayurveda_modifiers_applied": [...]}
    daily_exchange_allocation: Optional[Dict[str, float]] = None  # Daily exchange totals by category
    user_mandatory_applied: Optional[Dict[str, Any]] = None  # User-mandated exchanges information
    daily_exchange_summary: Optional[Dict[str, Any]] = None  # Daily exchange summary table (PDF format)
    exchange_distribution_table: Optional[Dict[str, Any]] = None  # Exchange distribution per meal table (PDF format)
    nutrient_distribution_per_meal: Optional[Dict[str, Any]] = None  # Nutrient distribution per meal table (PDF format)


@dataclass
class AyurvedaContext:
    """
    Ayurveda advisory context.
    
    Contains Ayurveda profile and lifestyle guidelines.
    """
    assessment_id: UUID
    dosha_primary: Optional[str] = None
    dosha_secondary: Optional[str] = None
    vikriti_notes: Optional[Dict[str, Any]] = None
    lifestyle_guidelines: Optional[Dict[str, Any]] = None


@dataclass
class InterventionContext:
    """
    Intervention stage context.
    
    Contains diet plan and intervention details.
    """
    client_id: UUID
    assessment_id: UUID
    plan_id: Optional[UUID] = None
    plan_version: Optional[int] = None
    meal_plan: Optional[Dict[str, Any]] = None
    explanations: Optional[Dict[str, Any]] = None
    constraints_snapshot: Optional[Dict[str, Any]] = None


@dataclass
class RecipeContext:
    """
    Recipe generation context.
    
    Contains complete meal recipes with instructions and nutrition.
    """
    assessment_id: UUID
    client_id: UUID
    plan_id: Optional[UUID] = None
    plan_version: Optional[int] = None
    meals_with_recipes: Optional[Dict[str, Any]] = None  # All meals with full recipes
    total_daily_nutrition: Optional[Dict[str, float]] = None
    meal_plan_structure: Optional[Dict[str, Any]] = None  # Original meal plan structure from FoodEngine


@dataclass
class MonitoringContext:
    """
    Monitoring stage context.
    
    Contains monitoring records and feedback.
    """
    client_id: UUID
    plan_id: UUID
    monitoring_records: list = field(default_factory=list)

