"""
Platform Exchange Allocation ORM model.
Stores exchange allocations per meal for an assessment.
"""
from datetime import datetime
from sqlalchemy import Column, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
import uuid
from app.database import Base


class PlatformExchangeAllocation(Base):
    """
    Platform exchange allocation model.
    
    Stores exchange allocations per meal generated by ExchangeSystemEngine.
    Links meal structure to food selection.
    """
    
    __tablename__ = "platform_exchange_allocations"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    assessment_id = Column(UUID(as_uuid=True), ForeignKey("platform_assessments.id"), nullable=False, unique=True)
    exchanges_per_meal = Column(JSONB, nullable=False)  # {"breakfast": {"cereal": 2, "pulse": 1, ...}, ...}
    daily_exchange_allocation = Column(JSONB, nullable=True)  # {"cereal": 2.5, "pulse": 1.5, ...} - Daily totals by category
    notes = Column(JSONB, nullable=True)  # {"medical_modifiers_applied": [...], "ayurveda_modifiers_applied": [...]}
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    assessment = relationship("PlatformAssessment", backref="exchange_allocations")
    
    def __repr__(self):
        return f"<PlatformExchangeAllocation {self.id}>"

